interface CStoreItemAssets {
  ConstructAssetURL(e, t): string | undefined;
  GetCommunityIconURL(): string | undefined;
  GetCommunityIconURL_Full(): string | undefined;
  GetHeaderURL(): string | undefined;
  GetHeroCapsuleURL(): string | undefined;
  GetHeroCapsuleURL_2x(): string | undefined;
  GetLibraryCapsuleURL(): string | undefined;
  GetLibraryCapsuleURL_2x(): string | undefined;
  GetLibraryHeroURL(): string | undefined;
  GetLibraryHeroURL_2x(): string | undefined;
  GetMainCapsuleURL(): string | undefined;
  GetPackageHeaderURL(): string | undefined;
  GetPageBackgroundURL(): string | undefined;
  GetRawPageBackgroundURL(): string | undefined;
  GetSmallCapsuleURL(): string | undefined;
}

export interface CStoreItem {
  k_regexSalePage: RegExp;
  m_Assets: CStoreItemAssets | undefined;
  m_AssetsWithoutOverrides: CStoreItemAssets | undefined;
  m_BasicInfo: {
    developers: {
      name: string;
    }[];
    franchises: {
      creator_clan_account_id: number;
      name: string;
    }[];
    publishers: {
      creator_clan_account_id: number;
      name: string;
    }[];
    short_description: string;
  };
  m_BestPurchaseOption: {
    active_discounts: {
      discount_amount: string;
      discount_description: string;
      discount_end_date: number;
    }[];
    discount_pct: number;
    final_price_in_cents: string;
    formatted_final_price: string;
    formatted_original_price: string;
    hide_discount_pct_for_compliance: boolean;
    included_game_count: number;
    original_price_in_cents: string;
    packageid: number;
    purchase_option_name: string;
    user_can_purchase_as_gift: boolean;
  };
  m_ContentDescriptorIDs: any[];
  m_DataRequested: {
    include_assets: boolean;
    include_basic_info: boolean;
    include_tag_count: number;
  };
  m_Platforms: any;
  m_RelatedItems: {
    demo_appid: any[];
    standalone_demo_appid: any[];
  };
  m_ReleaseInfo: any;
  m_ReviewInfo: any;
  m_Screenshots: any;
  m_SelfPurchaseOption: any;
  m_StoreCategories: {
    controller_categoryids: number[];
    feature_categoryids: number[];
    supported_player_categoryids: number[];
  };
  m_Trailers: any;
  m_bIsComingSoon: boolean;
  m_bIsEarlyAccess: boolean;
  m_bIsFree: boolean;
  m_bIsFreeTemporary: boolean;
  m_bVisible: boolean;
  m_eAppType: number;
  m_eItemType: number;
  m_freeWeekend: {};
  m_rgIncludedAppIDs: any[];
  m_rgIncludedAppTypes: any[];
  m_rgLinks: any;
  m_rgPurchaseOptions: any;
  m_rgStoreTagIDs: any[];
  m_rgStoreTags: any[];
  m_rgSupportedLanguages: any;
  m_strInternalName: any;
  m_strName: string;
  m_strStoreURLPath: string;
  m_strStoreURLPathOverride: any;
  m_unAppID: number;
  m_unID: number;
  m_userFilterFailure: any;

  BCheckDataRequestIncluded(e);
  BContainDataRequest(e);
  BHasAgeSafeScreenshots();
  BHasDemo();
  BHasHighlightTrailers(e);
  BHasSomeLanguageSupport(e);
  BHasStoreCategory(e);
  BHasTags();
  BHasTrailers(e);
  BIsAgeSafeScreenshot(e);
  BIsApplicationOrTool();
  BIsComingSoon();
  BIsCustomComingSoonDisplay();
  BIsEarlyAccess();
  BIsFree();
  BIsFreeTemporary();
  BIsFreeWeekend();
  BIsPrePurchase();
  BIsReleased();
  BIsSalePage();
  BIsVisible();
  BLimitedLaunchActive();
  GetAllCreatorClanIDs();
  GetAllDeveloperCreatorClans();
  GetAllFranchiseCreatorClans();
  GetAllLanguagesWithSomeSupport();
  GetAllPublisherCreatorClans();
  GetAllPurchaseOptions();
  GetAllTrailers();
  GetAppID();
  GetAppIDToRun();
  GetAppType();
  GetAssets();
  GetAssetsWithoutOverrides();
  GetBestPurchaseOption();
  GetBestPurchaseOriginalPriceFormatted();
  GetBestPurchaseOriginalPriceInCents();
  GetBestPurchasePriceFormatted();
  GetBestPurchasePriceInCents();
  GetCapsuleHeadline();
  GetCommunityDiscussionForumsURL();
  GetCommunityPageURL();
  GetContentDescriptorIDs();
  GetDataRequest();
  GetDemoAppIDs();
  GetDemoStandaloneStorePageAppIDs();
  GetDeveloperNames();
  GetFilteredReviewSummary();
  GetFilteredReviewSummaryLanguage();
  GetFormattedSteamReleaseDate();
  GetFranchiseNames();
  GetFreeWeekendEnd();
  GetFreeWeekendPlayTextOverride();
  GetID();
  GetIncludedAppIDs();
  GetIncludedAppIDsOrSelf();
  GetIncludedAppTypes();
  GetInternalName();
  GetLinks();
  GetMicroTrailer(e);
  GetName();
  GetOriginalReleaseDateRTime();
  GetParentAppID();
  GetPlatforms();
  GetPublisherNames();
  GetReleaseDateRTime(e?: boolean);
  GetSalePageVanityURL();
  GetScreenshots(e);
  GetSelfPurchaseOption();
  GetShortDescription();
  GetStoreCategories_Controller();
  GetStoreCategories_Features();
  GetStoreCategories_SupportedPlayers();
  GetStoreItemType();
  GetStorePageURL(e?: boolean);
  GetStorePageURLOverride();
  GetStorePageURLWithOverride();
  GetTagIDs();
  GetTags();
  GetUnfilteredReviewSummary();
  GetUniqueID();
  GetUserFilterFailure();
  HasContentDescriptorID(e);
  HasDemoStandaloneStorePage();
  MergeData(e, t);
  ReplaceBestPurchaseOption(e);
}
